### ISSUE TITLE
Can I watch multiple variables?

### ISSUE THREAD

**Issue by domoritz** [Blitzen/Angular-Chronicle#31]
I have an app with more than one scope variable that should be undoable. I'd like to watch changes of different variables but in the same undo/redo stack. How would I do that?

**Comment by duncanmcdowell** [comment]
Watch the object or collection and you shouldn't have a problem.

**Comment by domoritz** [comment]
Not sure I understand. 

This is what I have
```
var a = Chronicle.record('a', $scope);
var b = Chronicle.record('b', $scope);

$scope.undo = function() {
  ?? // which one to undo?
}
```

Are you suggesting
```
var wrapper = {
  state: {
    a: $scope.a,
    b: $scope.b
  }
}
var state = Chronicle.record('state', wrapper);

$scope.undo = function() {
  state.undo();
}
```

I tried it and the two way binding didn't work any more.

**Comment by SamMaier** [comment]
Sorry, what do you mean the two way binding didn't work? Can you give me a more specific example?

**Comment by domoritz** [comment]
With the second method, the object that I am referring to is not modified after an undo/redo. I'm seeing this issue in my large application so I cannot just refer to that. I'll look a bit more into what exactly is not updating. I was just wondering what the standard way to undo/redo multiple variables is.

**Comment by SamMaier** [comment]
Hmmm... As of right now this functionality isn't supported as you would like it. The "typical" undo/redo use case is that if you want to perform a single undo/redo on some selection of elements, your code would already have that selection grouped.

**Comment by domoritz** [comment]
Okay, I was not using this library properly. I just added all the variables I needed to the `noWatchVar` and triggered a change on the watched variable whenever I wanted a new state saved. Works flawlessly.

**Comment by vgavrilovikj** [comment]
Did you fix this? How do you watch two variables at the same time?
